name: concisely
description: A simple parser combinator library for Dart language.
# version: 0.0.1
# homepage: https://www.example.com
# author: umaranis <mail@umaranis.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
