name: concisely
description: A simple parser combinator library for Dart language.
# version: 0.0.1
# homepage: https://umaranis.com
# author: umaranis <mail@umaranis.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
  #coverage: ^1.0.3

dev_dependencies:
  test: ^1.18.2
  coverage: ^1.0.3
