name: concisely
description: A simple parser combinator library for Dart language.
# version: 0.0.1
# homepage: https://umaranis.com
# author: umaranis <mail@umaranis.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  test: ^1.16.5
