name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Code Coverage
      run: pub run test_coverage
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash) -t 022cedc6-d847-42fa-83b7-bcc7d87ac3e7
